"""
Integration tests for PyEPlan.

This module tests the complete PyEPlan workflow including:
- End-to-end data processing, routing, and optimization
- Integration between all modules
- Real-world example scenarios
"""

import unittest
import pandas as pd
import numpy as np
import os
import tempfile
import shutil
from unittest.mock import patch, MagicMock

# Import PyEPlan modules
import pyeplan
from pyeplan.dataproc import datsys
from pyeplan.routing import rousys
from pyeplan.investoper import inosys


class TestPyEPlanCompleteWorkflow(unittest.TestCase):
    """Test complete PyEPlan workflow."""

    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = tempfile.mkdtemp()
        self._create_complete_test_data()
        
    def tearDown(self):
        """Clean up test fixtures."""
        shutil.rmtree(self.test_dir)

    def _create_complete_test_data(self):
        """Create complete test dataset for end-to-end testing."""
        # Create mgpc_dist.xlsx with load point and load level data
        load_data = pd.DataFrame({
            'Load Point': [0, 1, 2],
            'Latitude': [0.25, 0.26, 0.27],
            'Longitude': [32.40, 32.41, 32.42]
        })
        
        load_levels = pd.DataFrame({
            'Load Level': [50, 75, 100]
        })
        
        with pd.ExcelWriter(os.path.join(self.test_dir, 'mgpc_dist.xlsx')) as writer:
            load_data.to_excel(writer, sheet_name='Load Point', index=False)
            load_levels.to_excel(writer, sheet_name='Load Level', index=False)
        
        # Create all required CSV files for the complete workflow
        self._create_generator_data()
        self._create_network_data()
        self._create_demand_data()
        self._create_renewable_data()

    def _create_generator_data(self):
        """Create generator data files."""
        # Conventional generators
        cgen_data = pd.DataFrame({
            'bus': [0, 1],
            'pmin': [0, 0],
            'pmax': [100, 100],
            'qmin': [-50, -50],
            'qmax': [50, 50],
            'icost': [1000, 1000],
            'ocost': [50, 50]
        })
        cgen_data.to_csv(os.path.join(self.test_dir, 'cgen_dist.csv'), index=False)
        
        # Existing generators
        egen_data = pd.DataFrame({
            'bus': [0],
            'pmin': [0],
            'pmax': [50],
            'qmin': [-25],
            'qmax': [25],
            'ocost': [60]
        })
        egen_data.to_csv(os.path.join(self.test_dir, 'egen_dist.csv'), index=False)
        
        # Solar PV
        csol_data = pd.DataFrame({
            'bus': [0, 1],
            'pmin': [0, 0],
            'pmax': [50, 50],
            'qmin': [-25, -25],
            'qmax': [25, 25],
            'icost': [800, 800],
            'ocost': [0, 0]
        })
        csol_data.to_csv(os.path.join(self.test_dir, 'csol_dist.csv'), index=False)
        
        esol_data = pd.DataFrame({
            'bus': [0],
            'pmin': [0],
            'pmax': [25],
            'qmin': [-12.5],
            'qmax': [12.5],
            'ocost': [0]
        })
        esol_data.to_csv(os.path.join(self.test_dir, 'esol_dist.csv'), index=False)
        
        # Wind turbines
        cwin_data = pd.DataFrame({
            'bus': [0, 1],
            'pmin': [0, 0],
            'pmax': [30, 30],
            'qmin': [-15, -15],
            'qmax': [15, 15],
            'icost': [1200, 1200],
            'ocost': [0, 0]
        })
        cwin_data.to_csv(os.path.join(self.test_dir, 'cwin_dist.csv'), index=False)
        
        ewin_data = pd.DataFrame({
            'bus': [0],
            'pmin': [0],
            'pmax': [15],
            'qmin': [-7.5],
            'qmax': [7.5],
            'ocost': [0]
        })
        ewin_data.to_csv(os.path.join(self.test_dir, 'ewin_dist.csv'), index=False)
        
        # Batteries
        cbat_data = pd.DataFrame({
            'bus': [0, 1],
            'emin': [0, 0],
            'emax': [100, 100],
            'eini': [50, 50],
            'pmin': [-25, -25],
            'pmax': [25, 25],
            'icost': [500, 500],
            'ocost': [0, 0]
        })
        cbat_data.to_csv(os.path.join(self.test_dir, 'cbat_dist.csv'), index=False)

    def _create_network_data(self):
        """Create network data files."""
        # Geographical data
        geol_data = pd.DataFrame({
            'Longtitude': [32.40, 32.41, 32.42],
            'Latitude': [0.25, 0.26, 0.27]
        })
        geol_data.to_csv(os.path.join(self.test_dir, 'geol_dist.csv'), index=False)
        
        # Cable data
        cable_data = pd.DataFrame({
            'crs': [35, 35, 35],
            'r7': [0.524, 0.524, 0.524],
            'x7': [0.084, 0.084, 0.084],
            'i7': [130, 130, 130]
        })
        cable_data.to_csv(os.path.join(self.test_dir, 'cblt_dist.csv'), index=False)
        
        # Electrical lines (will be generated by routing)
        elin_data = pd.DataFrame({
            'from': [0, 1],
            'to': [1, 2],
            'ini': [1, 1],
            'res': [0.1, 0.1],
            'rea': [0.05, 0.05],
            'sus': [0, 0],
            'pmax': [100, 100],
            'qmax': [50, 50]
        })
        elin_data.to_csv(os.path.join(self.test_dir, 'elin_dist.csv'), index=False)

    def _create_demand_data(self):
        """Create demand data files."""
        # Active power demand
        pdem_data = pd.DataFrame({
            '0': [50, 75, 100],
            '1': [60, 80, 110],
            '2': [40, 60, 80]
        })
        pdem_data.to_csv(os.path.join(self.test_dir, 'pdem_dist.csv'), index=False)
        
        # Reactive power demand
        qdem_data = pd.DataFrame({
            '0': [25, 37.5, 50],
            '1': [30, 40, 55],
            '2': [20, 30, 40]
        })
        qdem_data.to_csv(os.path.join(self.test_dir, 'qdem_dist.csv'), index=False)

    def _create_renewable_data(self):
        """Create renewable energy data files."""
        # Renewable profiles
        prep_data = pd.DataFrame({
            '0': [50, 75, 100],
            '1': [60, 80, 110],
            '2': [40, 60, 80]
        })
        prep_data.to_csv(os.path.join(self.test_dir, 'prep_dist.csv'), index=False)
        
        qrep_data = pd.DataFrame({
            '0': [25, 37.5, 50],
            '1': [30, 40, 55],
            '2': [20, 30, 40]
        })
        qrep_data.to_csv(os.path.join(self.test_dir, 'qrep_dist.csv'), index=False)
        
        # Solar scenarios
        psol_data = pd.DataFrame({
            '0': [20, 30, 40],
            '1': [25, 35, 45],
            '2': [15, 25, 35]
        })
        psol_data.to_csv(os.path.join(self.test_dir, 'psol_dist.csv'), index=False)
        
        qsol_data = pd.DataFrame({
            '0': [10, 15, 20],
            '1': [12.5, 17.5, 22.5],
            '2': [7.5, 12.5, 17.5]
        })
        qsol_data.to_csv(os.path.join(self.test_dir, 'qsol_dist.csv'), index=False)
        
        # Wind scenarios
        pwin_data = pd.DataFrame({
            '0': [10, 15, 20],
            '1': [12, 18, 24],
            '2': [8, 12, 16]
        })
        pwin_data.to_csv(os.path.join(self.test_dir, 'pwin_dist.csv'), index=False)
        
        qwin_data = pd.DataFrame({
            '0': [5, 7.5, 10],
            '1': [6, 9, 12],
            '2': [4, 6, 8]
        })
        qwin_data.to_csv(os.path.join(self.test_dir, 'qwin_dist.csv'), index=False)
        
        # Time duration
        dtim_data = pd.DataFrame({
            'dt': [8, 8, 8]
        })
        dtim_data.to_csv(os.path.join(self.test_dir, 'dtim_dist.csv'), index=False)

    @patch('urllib.request.urlopen')
    @patch('pyomo.environ.SolverFactory')
    def test_complete_workflow(self, mock_solver_factory, mock_urlopen):
        """Test complete PyEPlan workflow from data processing to optimization."""
        # Mock PVGIS API response
        mock_response = MagicMock()
        mock_response.read.return_value = b"Time,P,G(i),H_sun,T2m,WS10m,Int\n2020-01-02 00:00:00,0,0,0,25,2,0\n2020-01-02 01:00:00,10,100,10,26,3,0\n2020-01-02 02:00:00,20,200,20,27,4,0\n"
        mock_urlopen.return_value = mock_response
        
        # Mock solver
        mock_solver = MagicMock()
        mock_solver_factory.return_value = mock_solver
        mock_solver.solve.return_value = MagicMock()
        
        # Step 1: Data Processing
        data_sys = datsys(
            inp_folder=self.test_dir,
            lat=0.25,
            lon=32.40,
            year=2020,
            pvcalc=1,
            pp=50,
            n_clust=3
        )
        
        # Test data extraction
        data_sys.data_extract()
        self.assertIsNotNone(data_sys.data_local_time)
        self.assertIsNotNone(data_sys.PV_power)
        
        # Test clustering
        data_sys.kmeans_clust()
        
        # Verify clustering output files
        expected_cluster_files = ['psol_dist.csv', 'qsol_dist.csv', 'pwin_dist.csv', 'qwin_dist.csv', 'dtim_dist.csv']
        for filename in expected_cluster_files:
            filepath = os.path.join(self.test_dir, filename)
            self.assertTrue(os.path.exists(filepath), f"Clustering file {filename} was not created")
        
        # Step 2: Network Routing
        route_sys = rousys(
            inp_folder=self.test_dir,
            crs=35,
            typ=7,
            vbase=415,
            sbase=1
        )
        
        # Test minimum spanning tree generation
        route_sys.min_spn_tre()
        
        # Verify routing output files
        expected_routing_files = ['rou_dist.csv', 'elin_dist.csv']
        for filename in expected_routing_files:
            filepath = os.path.join(self.test_dir, filename)
            self.assertTrue(os.path.exists(filepath), f"Routing file {filename} was not created")
        
        # Step 3: Investment and Operation Optimization
        inv_sys = inosys(
            inp_folder=self.test_dir,
            ref_bus=0,
            dshed_cost=1000000,
            rshed_cost=500
        )
        
        # Verify data loading
        self.assertIsNotNone(inv_sys.cgen)
        self.assertIsNotNone(inv_sys.egen)
        self.assertIsNotNone(inv_sys.csol)
        self.assertIsNotNone(inv_sys.esol)
        self.assertIsNotNone(inv_sys.cwin)
        self.assertIsNotNone(inv_sys.ewin)
        self.assertIsNotNone(inv_sys.cbat)
        self.assertIsNotNone(inv_sys.elin)
        self.assertIsNotNone(inv_sys.pdem)
        self.assertIsNotNone(inv_sys.qdem)
        
        # Test optimization solve
        inv_sys.solve(solver='glpk', invest=True, onlyopr=False)
        
        # Verify solver was called
        mock_solver.solve.assert_called_once()
        
        # Verify results directory was created
        results_dir = os.path.join(self.test_dir, 'results')
        self.assertTrue(os.path.exists(results_dir), "Results directory was not created")

    def test_pyeplan_import(self):
        """Test that PyEPlan can be imported correctly."""
        # Test main module import
        self.assertIsNotNone(pyeplan)
        
        # Test individual module imports
        self.assertIsNotNone(pyeplan.datsys)
        self.assertIsNotNone(pyeplan.rousys)
        self.assertIsNotNone(pyeplan.inosys)
        
        # Test that classes are available
        self.assertTrue(hasattr(pyeplan, 'datsys'))
        self.assertTrue(hasattr(pyeplan, 'rousys'))
        self.assertTrue(hasattr(pyeplan, 'inosys'))

    def test_module_attributes(self):
        """Test that PyEPlan modules have correct attributes."""
        # Test datsys class attributes
        self.assertTrue(hasattr(datsys, '__init__'))
        self.assertTrue(hasattr(datsys, 'data_extract'))
        self.assertTrue(hasattr(datsys, 'kmeans_clust'))
        
        # Test rousys class attributes
        self.assertTrue(hasattr(rousys, '__init__'))
        self.assertTrue(hasattr(rousys, 'min_spn_tre'))
        
        # Test inosys class attributes
        self.assertTrue(hasattr(inosys, '__init__'))
        self.assertTrue(hasattr(inosys, 'solve'))
        self.assertTrue(hasattr(inosys, 'resCost'))
        self.assertTrue(hasattr(inosys, 'resSolar'))
        self.assertTrue(hasattr(inosys, 'resWind'))
        self.assertTrue(hasattr(inosys, 'resBat'))
        self.assertTrue(hasattr(inosys, 'resConv'))
        self.assertTrue(hasattr(inosys, 'resCurt'))


class TestPyEPlanExamples(unittest.TestCase):
    """Test PyEPlan using real example data."""

    def setUp(self):
        """Set up test fixtures with real example data."""
        self.example_dirs = {
            '5_bus': 'examples/5_bus',
            '1_bus': 'examples/1_bus',
            'wat_inv': 'examples/wat_inv'
        }
        
        # Check which example data is available
        self.available_examples = {}
        for name, path in self.example_dirs.items():
            if os.path.exists(path):
                self.available_examples[name] = path

    def test_5_bus_example_data(self):
        """Test with 5-bus microgrid example data."""
        if '5_bus' not in self.available_examples:
            self.skipTest("5_bus example data not available")
        
        example_dir = self.available_examples['5_bus']
        
        # Test data loading
        inv_sys = inosys(inp_folder=example_dir, ref_bus=0)
        
        # Verify data loading
        self.assertIsNotNone(inv_sys.cgen)
        self.assertIsNotNone(inv_sys.egen)
        self.assertIsNotNone(inv_sys.csol)
        self.assertIsNotNone(inv_sys.esol)
        self.assertIsNotNone(inv_sys.cwin)
        self.assertIsNotNone(inv_sys.ewin)
        self.assertIsNotNone(inv_sys.cbat)
        self.assertIsNotNone(inv_sys.elin)
        self.assertIsNotNone(inv_sys.pdem)
        self.assertIsNotNone(inv_sys.qdem)
        
        # Check component counts
        self.assertGreaterEqual(inv_sys.ncg, 0)
        self.assertGreaterEqual(inv_sys.neg, 0)
        self.assertGreaterEqual(inv_sys.ncs, 0)
        self.assertGreaterEqual(inv_sys.nes, 0)
        self.assertGreaterEqual(inv_sys.ncw, 0)
        self.assertGreaterEqual(inv_sys.new, 0)
        self.assertGreaterEqual(inv_sys.ncb, 0)
        self.assertGreaterEqual(inv_sys.nel, 0)
        self.assertGreater(inv_sys.nbb, 0)
        self.assertGreater(inv_sys.ntt, 0)
        self.assertGreater(inv_sys.noo, 0)

    def test_1_bus_example_data(self):
        """Test with 1-bus standalone system example data."""
        if '1_bus' not in self.available_examples:
            self.skipTest("1_bus example data not available")
        
        example_dir = self.available_examples['1_bus']
        
        # Test data loading
        inv_sys = inosys(inp_folder=example_dir, ref_bus=0)
        
        # Verify data loading
        self.assertIsNotNone(inv_sys.cgen)
        self.assertIsNotNone(inv_sys.egen)
        self.assertIsNotNone(inv_sys.csol)
        self.assertIsNotNone(inv_sys.esol)
        self.assertIsNotNone(inv_sys.cwin)
        self.assertIsNotNone(inv_sys.ewin)
        self.assertIsNotNone(inv_sys.cbat)
        self.assertIsNotNone(inv_sys.elin)
        self.assertIsNotNone(inv_sys.pdem)
        self.assertIsNotNone(inv_sys.qdem)

    def test_wat_inv_example_data(self):
        """Test with Watoto Village investment example data."""
        if 'wat_inv' not in self.available_examples:
            self.skipTest("wat_inv example data not available")
        
        example_dir = self.available_examples['wat_inv']
        
        # Test data loading
        inv_sys = inosys(inp_folder=example_dir, ref_bus=0)
        
        # Verify data loading
        self.assertIsNotNone(inv_sys.cgen)
        self.assertIsNotNone(inv_sys.egen)
        self.assertIsNotNone(inv_sys.csol)
        self.assertIsNotNone(inv_sys.esol)
        self.assertIsNotNone(inv_sys.cwin)
        self.assertIsNotNone(inv_sys.ewin)
        self.assertIsNotNone(inv_sys.cbat)
        self.assertIsNotNone(inv_sys.elin)
        self.assertIsNotNone(inv_sys.pdem)
        self.assertIsNotNone(inv_sys.qdem)

    @patch('urllib.request.urlopen')
    def test_routing_with_example_data(self, mock_urlopen):
        """Test routing with real example data."""
        if '5_bus' not in self.available_examples:
            self.skipTest("5_bus example data not available")
        
        example_dir = self.available_examples['5_bus']
        
        # Test routing with real data
        route_sys = rousys(
            inp_folder=example_dir,
            crs=35,
            typ=7,
            vbase=415,
            sbase=1
        )
        
        # Test minimum spanning tree generation
        route_sys.min_spn_tre()
        
        # Verify that the system can process real data
        self.assertIsNotNone(route_sys.geol)
        self.assertIsNotNone(route_sys.cblt)
        self.assertGreater(route_sys.node, 0)
        
        # Check that output files were created
        expected_files = ['rou_dist.csv', 'elin_dist.csv']
        for filename in expected_files:
            filepath = os.path.join(example_dir, filename)
            self.assertTrue(os.path.exists(filepath), f"File {filename} was not created")


class TestPyEPlanErrorHandling(unittest.TestCase):
    """Test PyEPlan error handling and edge cases."""

    def test_missing_data_files(self):
        """Test handling of missing data files."""
        # Create empty directory
        test_dir = tempfile.mkdtemp()
        
        try:
            # Test that appropriate errors are raised for missing files
            with self.assertRaises(FileNotFoundError):
                inosys(inp_folder=test_dir, ref_bus=0)
        finally:
            shutil.rmtree(test_dir)

    def test_invalid_parameters(self):
        """Test handling of invalid parameters."""
        # Create minimal test data
        test_dir = tempfile.mkdtemp()
        
        try:
            # Create minimal required files
            pd.DataFrame({'bus': [0], 'pmin': [0], 'pmax': [100], 'qmin': [-50], 'qmax': [50], 'icost': [1000], 'ocost': [50]}).to_csv(os.path.join(test_dir, 'cgen_dist.csv'), index=False)
            pd.DataFrame({'bus': [0], 'pmin': [0], 'pmax': [50], 'qmin': [-25], 'qmax': [25], 'ocost': [60]}).to_csv(os.path.join(test_dir, 'egen_dist.csv'), index=False)
            pd.DataFrame({'0': [50, 75, 100]}).to_csv(os.path.join(test_dir, 'pdem_dist.csv'), index=False)
            pd.DataFrame({'0': [25, 37.5, 50]}).to_csv(os.path.join(test_dir, 'qdem_dist.csv'), index=False)
            pd.DataFrame({'0': [50, 75, 100]}).to_csv(os.path.join(test_dir, 'prep_dist.csv'), index=False)
            pd.DataFrame({'0': [25, 37.5, 50]}).to_csv(os.path.join(test_dir, 'qrep_dist.csv'), index=False)
            pd.DataFrame({'0': [20, 30, 40]}).to_csv(os.path.join(test_dir, 'psol_dist.csv'), index=False)
            pd.DataFrame({'0': [10, 15, 20]}).to_csv(os.path.join(test_dir, 'qsol_dist.csv'), index=False)
            pd.DataFrame({'0': [10, 15, 20]}).to_csv(os.path.join(test_dir, 'pwin_dist.csv'), index=False)
            pd.DataFrame({'0': [5, 7.5, 10]}).to_csv(os.path.join(test_dir, 'qwin_dist.csv'), index=False)
            pd.DataFrame({'dt': [8, 8, 8]}).to_csv(os.path.join(test_dir, 'dtim_dist.csv'), index=False)
            
            # Test with invalid reference bus
            with self.assertRaises((KeyError, IndexError)):
                inv_sys = inosys(inp_folder=test_dir, ref_bus=999)
                
        finally:
            shutil.rmtree(test_dir)


if __name__ == '__main__':
    unittest.main() 